In [23]:
from heart_disease.data.ingestion import load_csv
from heart_disease.config import RAW_DATA_DIR, INTERIM_DATA_DIR
from heart_disease.features.cleaning import clean_data, calculate_missing_data

In [24]:
df = load_csv(RAW_DATA_DIR / "heart_disease_uci.csv")
df = df.drop(columns=["id"])
df.head()

,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [25]:
calculate_missing_data(df)

          Percentage of missing data
ca                         66.413043
thal                       52.826087
slope                      33.586957
fbs                         9.782609
oldpeak                     6.739130
trestbps                    6.413043
thalch                      5.978261
exang                       5.978261
chol                        3.260870
restecg                     0.217391
dataset                     0.000000
cp                          0.000000
age                         0.000000
sex                         0.000000
num                         0.000000

In [26]:
df.isna().sum(axis=1).value_counts().sort_index(ascending=True)

0    299
1     74
2    208
3    253
4     29
5      3
6      1
7     51
8      2
Name: count, dtype: int64

In [27]:
df = clean_data(df)

2026-08-18 19:16:47,972 | INFO | heart_disease.features.cleaning | Replacing 172 non-positive chol values to nan.
2026-08-18 19:16:47,979 | INFO | heart_disease.features.cleaning | Replacing 1 non-positive trestbps values to nan.
2026-08-18 19:16:47,994 | INFO | heart_disease.features.cleaning | Replacing 382 non-positive oldpeak values to nan.
2026-08-18 19:16:48,004 | INFO | heart_disease.features.cleaning | Converting target to binary

In [28]:
df.isna().sum(axis=1).value_counts().sort_index(ascending=True)

0    203
1    119
2    163
3     98
4    231
5     50
6      2
7     43
8     11
Name: count, dtype: int64

In [29]:
calculate_missing_data(df)

          Percentage of missing data
ca                         66.413043
thal                       52.826087
oldpeak                    48.260870
slope                      33.586957
chol                       21.956522
fbs                         9.782609
trestbps                    6.521739
thalch                      5.978261
exang                       5.978261
restecg                     0.217391
dataset                     0.000000
cp                          0.000000
age                         0.000000
sex                         0.000000
target                      0.000000

In [32]:
df.shape

(920, 15)

In [31]:
df.to_csv(INTERIM_DATA_DIR / "cleaned_dataset.csv", index=False)