In [1]:
from heart_disease.data.ingestion import load_file
from heart_disease.config import MODEL_DIR, INTERIM_DATA_DIR, ExperimentConfig
from heart_disease.models.train import load_model
from heart_disease.models.evaluation import (
    evaluate_model,
    get_confusion_matrix,
    get_classification_report,
)
from heart_disease.models.interpretation import get_feature_coefficients

In [2]:
X_test = load_file(INTERIM_DATA_DIR / "X_test.parquet")
y_test = load_file(INTERIM_DATA_DIR / "y_test.parquet")["target"]

final_lr_model = load_model(MODEL_DIR / "logistic_regression.joblib")

2026-09-17 18:50:32,181 | INFO | heart_disease.models.train | Loading LogisticRegression model from /home/irasionize/heart-disease-ml/models/logistic_regression.joblib

In [3]:
evaluate_model(final_lr_model, X_test, y_test, ExperimentConfig())

2026-09-17 18:50:32,210 | INFO | heart_disease.models.evaluation | Evaluating LogisticRegression on test data.
2026-09-17 18:50:32,596 | INFO | heart_disease.models.evaluation | Test metrics | Accuracy: 0.837 | Precision: 0.805 | Recall: 0.931 | F1: 0.864 | ROC-AUC: 0.911

🏃 View run LogisticRegression-final-evaluation at: http://127.0.0.1:5000/#/experiments/1/runs/af19b6136922479188657e5509e4121e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

{'accuracy': 0.8369565217391305,
 'precision': 0.8050847457627118,
 'recall': 0.9313725490196079,
 'f1': 0.8636363636363636,
 'roc_auc': 0.9110473457675753}

In [4]:
get_confusion_matrix(final_lr_model, X_test, y_test)

          Predicted 0  Predicted 1
Actual 0           59           23
Actual 1            7           95

In [5]:
get_classification_report(final_lr_model, X_test, y_test)

              precision    recall  f1-score     support
0              0.893939  0.719512  0.797297   82.000000
1              0.805085  0.931373  0.863636  102.000000
accuracy       0.836957  0.836957  0.836957    0.836957
macro avg      0.849512  0.825442  0.830467  184.000000
weighted avg   0.844683  0.836957  0.834072  184.000000

In [6]:
get_feature_coefficients(final_lr_model)

                                      feature  coefficient  odds_ratio
0                         categorical__ca_0.0    -1.725529    0.178079
1             categorical__cp_atypical angina    -0.766583    0.464598
2    categorical__missingindicator_slope_True    -0.662483    0.515569
3                    categorical__thal_normal    -0.629916    0.532636
4      categorical__missingindicator_ca_False    -0.534448    0.585993
5                     categorical__sex_Female    -0.477068    0.620601
6     categorical__missingindicator_fbs_False    -0.444032    0.641445
7                    categorical__exang_False    -0.359677    0.697902
8                 categorical__restecg_normal    -0.248914    0.779647
9                 categorical__cp_non-anginal    -0.232932    0.792207
10                            numeric__thalch    -0.178473    0.836546
11           numeric__missingindicator_thalch    -0.102317    0.902743
12               categorical__slope_upsloping    -0.068153    0.934117
13             categorical__slope_downsloping    -0.038081    0.962635
14                     categorical__fbs_False    -0.000415    0.999585
15        categorical__restecg_lv hypertrophy     0.000000    1.000000
16  categorical__missingindicator_exang_False     0.000000    1.000000
17                        categorical__ca_1.0     0.000000    1.000000
18    categorical__missingindicator_thal_True     0.000000    1.000000
19   categorical__missingindicator_exang_True     0.000000    1.000000
20             categorical__thal_fixed defect     0.000000    1.000000
21      categorical__restecg_st-t abnormality     0.002915    1.002919
22   categorical__missingindicator_thal_False     0.058188    1.059914
23         numeric__missingindicator_trestbps     0.065814    1.068028
24          numeric__missingindicator_oldpeak     0.070779    1.073344
25                          numeric__trestbps     0.111150    1.117563
26                      categorical__fbs_True     0.198406    1.219458
27                              numeric__chol     0.218735    1.244502
28                               numeric__age     0.262715    1.300456
29             categorical__cp_typical angina     0.269814    1.309721
30             numeric__missingindicator_chol     0.286367    1.331581
31                        categorical__ca_3.0     0.303246    1.354247
32                        categorical__ca_2.0     0.318612    1.375218
33        categorical__thal_reversable defect     0.439140    1.551372
34                           numeric__oldpeak     0.569082    1.766644
35                    categorical__exang_True     0.581967    1.789555
36     categorical__missingindicator_fbs_True     0.666307    1.947033
37                      categorical__sex_Male     0.699362    2.012467
38      categorical__missingindicator_ca_True     0.756739    2.131314
39  categorical__missingindicator_slope_False     0.884789    2.422474
40               categorical__cp_asymptomatic     0.957831    2.606037
41                    categorical__slope_flat     0.998766    2.714929