In [1]:

from heart_disease.data.ingestion import load_file
from heart_disease.config import MODEL_DIR, INTERIM_DATA_DIR
from heart_disease.models.train import load_model
from heart_disease.models.evaluation import (
    evaluate_model,
    get_confusion_matrix,
    get_classification_report,
)

In [2]:
X_test = load_file(INTERIM_DATA_DIR / "X_test.parquet")
y_test = load_file(INTERIM_DATA_DIR / "y_test.parquet")["target"]

final_lr_model = load_model(MODEL_DIR / "logistic_regression.joblib")

2026-08-31 23:55:15,867 | INFO | heart_disease.models.train | Loading LogisticRegression model from /home/irasionize/heart-disease-ml/models/logistic_regression.joblib

In [8]:
evaluate_model(final_lr_model, X_test, y_test)

2026-08-31 23:57:41,219 | INFO | heart_disease.models.evaluation | Evaluating LogisticRegression on test data.

2026-08-31 23:57:41,427 | INFO | heart_disease.models.evaluation | Test metrics | Accuracy: 0.837 | Precision: 0.805 | Recall: 0.931 | F1: 0.864 | ROC-AUC: 0.911

{'accuracy': 0.8369565217391305,
 'precision': 0.8050847457627118,
 'recall': 0.9313725490196079,
 'f1': 0.8636363636363636,
 'roc_auc': 0.9111669057867049}

In [6]:
get_confusion_matrix(final_lr_model, X_test, y_test)

          Predicted 0  Predicted 1
Actual 0           59           23
Actual 1            7           95

In [7]:
get_classification_report(final_lr_model, X_test, y_test)

              precision    recall  f1-score     support
0              0.893939  0.719512  0.797297   82.000000
1              0.805085  0.931373  0.863636  102.000000
accuracy       0.836957  0.836957  0.836957    0.836957
macro avg      0.849512  0.825442  0.830467  184.000000
weighted avg   0.844683  0.836957  0.834072  184.000000